---
variables:
  PRODUCT: &PRODUCT 90427
  BASE_URL: &BASE_URL /home/joke/Documents/
  #/path/to/product/build/doc/    # CHANGE THIS

json_folder: [*BASE_URL, *PRODUCT, /database.json]
# URL: [*BASE_URL, *PRODUCT, /rom/html/document.html#id]
html_dir: [*BASE_URL, *PRODUCT, html]

# Keep this order !
filters:
  - SYSRQT
  - SWRQT
  - SWARCH
  - DESIGN
  - QTEST
  - SWITEST
  - UTEST

# Keep this order !
group_colors:
  SYSRQT: "#fc851c"
  SWRQT: "#FF33CC"
  SWARCH: "#7777FF"
  DESIGN: "#cf5402"
  QTEST: "#00FF00"
  SWITEST: "#00FF00"
  UTEST: "#00FF00"
  others: "black"

link_colors:
  impacts_on: "yellow"
  fulfilled_by: "violet"
  realized_by: "teal"
  validated_by: "thistle"
  reported_by: "skyblue"
  configurable_by: "purple"
  passed_by: "green"
  failed_by: "red"
  skipped_by: "orange"
  is_attribute_of: "palegreen"
  ext_polarion_reference: "navy"
  ext_polarion_revision: "lightslategrey"
  ext_jira_reference: "khaki"
  ext_robotframeworklog: "aquamarine"
  raised_by: "brown"
  guaranteed_by: "darkgreen"
  others: "black"

backwards_relationships:
  depends_on: 'impacts_on'
  fulfills: 'fulfilled_by'
  realizes: 'realized_by'
  validates: 'validated_by'
  reports_for: 'reported_by'
  configures: 'configurable_by'
  passes: 'passed_by'
  fails: 'failed_by'
  skipped: 'skipped_by'
  has_attribute: 'is_attribute_of'
  ext_polarion_reference: ''
  ext_polarion_revision: ''
  ext_jira_reference: ''
  ext_robotframeworklog: ''
  raises: 'raised_by'
  guarantees: 'guaranteed_by'

