---
variables:
  PRODUCT: &PRODUCT 90427
  BASE_URL: &BASE_URL /path/to/product/build/doc/    # CHANGE THIS

project: MLX{product}

json_folder: [*BASE_URL, *PRODUCT, /database.json]
# URL: [*BASE_URL, *PRODUCT, /rom/html/document.html#id]
URL: [*BASE_URL, *PRODUCT, /html/document.html#id]

# Keep this order !
filters:
  - SYSRQT
  - SWRQT
  - SWARCH
  - DESIGN
  - QTEST
  - SWITEST
  - UTEST

# Keep this order !
group_colors:
  SYSRQT: "#fc851c"
  SWRQT: "#FF33CC"
  SWARCH: "#7777FF"
  DESIGN: "#cf5402"
  QTEST: "#00FF00"
  SWITEST: "#00FF00"
  UTEST: "#00FF00"

link_colors:
  impacts_on: "#fc0303"
  fulfilled_by: "#13a300"
  depends_on: "#00a396"
  configurable_by: "#001ea3"
  implements: "#b1ba02"
  implemented_by: "#6f0182"
  realizes: "#499161"
  realized_by: "#820101"
  fulfills: "#ff9b05"
  validates: "#277a7a"
  validated_by: "#27597a"
  passed_by: "#8c00ff"
  passes: "#2b00ff"
  guaranteed_by: "#ffdd00"
  guaranteed: "#ff6f00"
  ext_polarion_reference: "#01173b"
  test_setup_used: "#006699"
  is_attribute_of: "#009900"
