services:
  app:
    build: 
      context: .
      args:
        - CONFIG_FILE="../config.yml"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runscript create_database &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - CONFIG_FILE=${CONFIG_FILE}
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j:5.7.0
    volumes:
      - '$HOME/neo4j/data:/data'
    environment:
      - NEO4J_AUTH=neo4j/password
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure

