version: '3.9'
services:
  app:
    build:
      context: .
      args:
        CONFIG_FILE: "config.yml"
        JSON_EXPORT: $JSON_EXPORT
        BASE_URL: "https://swdocs.sofia.elex.be/swcc/projects"
      # args:
      #   - CONFIG_FILE="../config.yml"
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      neo4j_db:
        condition: service_healthy
      # - neo4j_db
    links:
      - neo4j_db
    # volumes:
    #   - ./app:/app
    command: >
      sh -c "/py/bin/python3 manage.py runscript create_database &&
      /py/bin/python3 manage.py runserver"
    # networks:
    #   - mynetwork
    # environment:
    #   - CONFIG_FILE=${CONFIG_FILE}
    environment:
      - NEO4J_BOLT_URL=bolt://neo4j:password@neo4j_db:7687
      # - DJANGO_SETTINGS_MODULE=settings

  neo4j_db:
    image: neo4j:5.7.0
    volumes:
      - neo4j_db:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7474
      - 7687
    # networks:
    #   - mynetwork
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

volumes:
  neo4j_db:

# networks:
#   mynetwork:
#     driver: bridge
