version: '3'

services:
  backend:
    build:
    command: python manage.py runserver localhost:8000
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - neo4j
    links:
      - neo4j
    environment:
      - NEO4J_BOLT_URL=bolt://localhost:7687
      - DJANGO_SETTINGS_MODULE=settings

  neo4j:
    image: neo4j:5.7.0-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7474
      - 7687
    volumes:
      - db:/data/dbms
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687

volumes:
  db:
